[build]
  publish = "dist"
  command = "npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
  # CSP ajustada: se a침ade data: a font-src para permitir fuentes embebidas (woff base64) evitando el bloqueo visto en producci칩n.
  # Mantener lo m치s restrictiva posible preservando funcionalidades (GA, Meta Pixel, fuentes Google, im치genes externas seguras).
  Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com data: blob:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://connect.facebook.net; connect-src 'self' https://script.google.com https://www.google-analytics.com https://www.facebook.com https://connect.facebook.net https://www.googletagmanager.com https://cors.sh;"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Forms
[[forms]]
  name = "contact"

[functions]
  directory = "netlify/functions"
