name: "Copilot Setup Steps"

# Configuración automática para GitHub Copilot Coding Agent
# Se ejecuta cuando Copilot necesita configurar el entorno de desarrollo

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # El job DEBE llamarse 'copilot-setup-steps'
  # para que Copilot lo detecte automáticamente
  copilot-setup-steps:
    runs-on: ubuntu-latest

    permissions:
      # Permisos necesarios para clonar el repo
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build project
        run: npm run build

      - name: Run tests (if available)
        run: npm test --if-present

      - name: Lint code
        run: npm run lint --if-present

      - name: Preview build
        run: npm run preview &
        env:
          CI: true
